sonar.projectKey=boarding-house-management-level-3
sonar.projectName=Boarding House Management Level 3
sonar.projectVersion=3.0
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**,Lv1/**,billing-service/**,.npm-cache/**,monitoring/**,load-tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
